"""
Django settings for bookstore project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
<<<<<<< HEAD
=======
import sys

import dj_database_url
>>>>>>> 863831ccf4a6d1e4690c678d0b04d9751556a46e
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-_264m@l!!j#bsoaac@)v72+@u_tplzp91ava3j-_7wadm(=@ef")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
=======
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-_264m@l!!j#bsoaac@)v72+@u_tplzp91ava3j-_7wadm(=@ef",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in {"1", "true", "yes", "on"}
TESTING = (
    "test" in sys.argv
    or any("pytest" in arg for arg in sys.argv)
    or "PYTEST_CURRENT_TEST" in os.environ
)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1,.onrender.com,.herokuapp.com",
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://*.onrender.com",
    ).split(",")
    if origin.strip()
]
>>>>>>> 863831ccf4a6d1e4690c678d0b04d9751556a46e


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "django_extensions",
    "product",
    "order",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise middleware to serve static files in production
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if not TESTING:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "bookstore.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bookstore.wsgi.application"


# Database
# For local development/testing (DEBUG=True) use SQLite to avoid
# requiring a Postgres driver to run checks. In production (DEBUG=False)
# use Postgres configured via environment variables.
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

<<<<<<< HEAD
if DEBUG:
=======
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
        )
    }
else:
>>>>>>> 863831ccf4a6d1e4690c678d0b04d9751556a46e
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
<<<<<<< HEAD
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "bookstore"),
            "USER": os.environ.get("DB_USER", "bookstore"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "bookstore"),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
=======
>>>>>>> 863831ccf4a6d1e4690c678d0b04d9751556a46e
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

<<<<<<< HEAD
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# WhiteNoise: enable compressed static files and caching
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
=======
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

if not DEBUG and not TESTING:
    # Render forwards the original protocol; this allows Django to detect HTTPS correctly.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
>>>>>>> 863831ccf4a6d1e4690c678d0b04d9751556a46e


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# CONFIGURAÇÃO DE AUTENTICAÇÃO - DJANGO REST FRAMEWORK
# ============================================================================
# O que foi implementado:
# - Autenticação por Token personalizada (CustomTokenAuthentication)
# - Permissão padrão: IsAuthenticated (requer autenticação para acessar endpoints)
# - Paginação: PageNumberPagination com 10 itens por página
#
# Endpoints públicos (sem autenticação):
# - POST /api/auth/register/ - Registrar novo usuário
# - POST /api/auth/login/ - Fazer login e obter token
#
# Endpoints protegidos (requerem token):
# - POST /api/auth/logout/ - Fazer logout (requer token)
# - GET/POST /bookstore/v1/orders/ - Pedidos (requerem token)
#
# Endpoints públicos (sem autenticação por configuração específica):
# - GET /bookstore/v1/products/ - Produtos (removida proteção)
# - GET /bookstore/v1/categories/ - Categorias (removida proteção)
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'bookstore.authentication.CustomTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
